version: '3'

services:
  backend:
    container_name: 'prod-backend'
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  postgres:
    container_name: 'prod-database'
    image: postgres:12.12-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file: .env

  frontend:
    container_name: 'prod-frontend'
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/nginx/conf.d:/etc/nginx/conf.d
      - etc-letsencrypt:/etc/letsencrypt
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - certbot

  certbot:
    image: certbot/cerbot
    depends_on:
      - nginx
    container_name: cerbot
    volumes:
      - etc-letsencrypt:/etc/letsencrypt
      - www-html:/var/www/html
    command:  certonly --webroot --webroot-payh=/var/www/html --email final-task@mail.ru --agree-tos --no-eff-email --staging -d api.mesto.baranov.nomoredomains.work -d   mesto.baranov.nomoredomains.work

  volumes:
    www-html:
    dbfile:
    etc-letsencrypt: