version: '3'

services:
  backend:
    container_name: 'prod-backend'
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  postgres:
    container_name: 'prod-database'
    image: postgres:12.12-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file: .env

  frontend:
    container_name: 'prod-frontend'
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot/:ro
    ports:
      - '80:80/tcp'
      - '443:443/tcp'

  certbot:
    image: certbot/cerbot:latest
    auth:
      username: DimaBSammi
      password: 63d8c18fe658e07a5533f49e
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw